/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountHelpRouteImport } from './routes/account-help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiSupportRouteImport } from './routes/api/support'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as LoginVerifyRouteImport } from './routes/login_.verify'
import { Route as AuthenticatedScousGiftCardExchangeAdminRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppTradeRouteImport } from './routes/_authenticated/app.trade'
import { Route as AuthenticatedAppWithdrawRouteImport } from './routes/_authenticated/app.withdraw'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedScousGiftCardExchangeAdminIndexRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.index'
import { Route as AuthenticatedScousGiftCardExchangeAdminAuditRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.audit'
import { Route as AuthenticatedScousGiftCardExchangeAdminClosuresRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.closures'
import { Route as AuthenticatedScousGiftCardExchangeAdminMailRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.mail'
import { Route as AuthenticatedScousGiftCardExchangeAdminMessagesRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.messages'
import { Route as AuthenticatedScousGiftCardExchangeAdminRatesRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.rates'
import { Route as AuthenticatedScousGiftCardExchangeAdminTradesRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.trades'
import { Route as AuthenticatedScousGiftCardExchangeAdminUsersRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.users'
import { Route as AuthenticatedScousGiftCardExchangeAdminWithdrawalsRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.withdrawals'
import { Route as AuthenticatedAppHistoryIndexRouteImport } from './routes/_authenticated/app.history.index'
import { Route as AuthenticatedAppHistoryTradeIdRouteImport } from './routes/_authenticated/app.history.$tradeId'
import { Route as AuthenticatedScousGiftCardExchangeAdminTradesIdRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.trades.$id'
import { Route as AuthenticatedScousGiftCardExchangeAdminUsersIdRouteImport } from './routes/_authenticated/ScousGiftCardExchange.admin.users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHelpRoute = AccountHelpRouteImport.update({
  id: '/account-help',
  path: '/account-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login_/verify',
  path: '/login/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScousGiftCardExchangeAdminRoute =
  AuthenticatedScousGiftCardExchangeAdminRouteImport.update({
    id: '/ScousGiftCardExchange/admin',
    path: '/ScousGiftCardExchange/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTradeRoute = AuthenticatedAppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWithdrawRoute =
  AuthenticatedAppWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScousGiftCardExchangeAdminIndexRoute =
  AuthenticatedScousGiftCardExchangeAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminAuditRoute =
  AuthenticatedScousGiftCardExchangeAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminClosuresRoute =
  AuthenticatedScousGiftCardExchangeAdminClosuresRouteImport.update({
    id: '/closures',
    path: '/closures',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminMailRoute =
  AuthenticatedScousGiftCardExchangeAdminMailRouteImport.update({
    id: '/mail',
    path: '/mail',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminMessagesRoute =
  AuthenticatedScousGiftCardExchangeAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminRatesRoute =
  AuthenticatedScousGiftCardExchangeAdminRatesRouteImport.update({
    id: '/rates',
    path: '/rates',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminTradesRoute =
  AuthenticatedScousGiftCardExchangeAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminUsersRoute =
  AuthenticatedScousGiftCardExchangeAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute =
  AuthenticatedScousGiftCardExchangeAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminRoute,
  } as any)
const AuthenticatedAppHistoryIndexRoute =
  AuthenticatedAppHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppHistoryRoute,
  } as any)
const AuthenticatedAppHistoryTradeIdRoute =
  AuthenticatedAppHistoryTradeIdRouteImport.update({
    id: '/$tradeId',
    path: '/$tradeId',
    getParentRoute: () => AuthenticatedAppHistoryRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminTradesIdRoute =
  AuthenticatedScousGiftCardExchangeAdminTradesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminTradesRoute,
  } as any)
const AuthenticatedScousGiftCardExchangeAdminUsersIdRoute =
  AuthenticatedScousGiftCardExchangeAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedScousGiftCardExchangeAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-help': typeof AccountHelpRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/avatar': typeof ApiAvatarRoute
  '/api/support': typeof ApiSupportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/login/verify': typeof LoginVerifyRoute
  '/ScousGiftCardExchange/admin': typeof AuthenticatedScousGiftCardExchangeAdminRouteWithChildren
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/history': typeof AuthenticatedAppHistoryRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trade': typeof AuthenticatedAppTradeRoute
  '/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/ScousGiftCardExchange/admin/audit': typeof AuthenticatedScousGiftCardExchangeAdminAuditRoute
  '/ScousGiftCardExchange/admin/closures': typeof AuthenticatedScousGiftCardExchangeAdminClosuresRoute
  '/ScousGiftCardExchange/admin/mail': typeof AuthenticatedScousGiftCardExchangeAdminMailRoute
  '/ScousGiftCardExchange/admin/messages': typeof AuthenticatedScousGiftCardExchangeAdminMessagesRoute
  '/ScousGiftCardExchange/admin/rates': typeof AuthenticatedScousGiftCardExchangeAdminRatesRoute
  '/ScousGiftCardExchange/admin/trades': typeof AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren
  '/ScousGiftCardExchange/admin/users': typeof AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren
  '/ScousGiftCardExchange/admin/withdrawals': typeof AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute
  '/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
  '/ScousGiftCardExchange/admin/': typeof AuthenticatedScousGiftCardExchangeAdminIndexRoute
  '/app/history/': typeof AuthenticatedAppHistoryIndexRoute
  '/ScousGiftCardExchange/admin/trades/$id': typeof AuthenticatedScousGiftCardExchangeAdminTradesIdRoute
  '/ScousGiftCardExchange/admin/users/$id': typeof AuthenticatedScousGiftCardExchangeAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-help': typeof AccountHelpRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/support': typeof ApiSupportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/login/verify': typeof LoginVerifyRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trade': typeof AuthenticatedAppTradeRoute
  '/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/ScousGiftCardExchange/admin/audit': typeof AuthenticatedScousGiftCardExchangeAdminAuditRoute
  '/ScousGiftCardExchange/admin/closures': typeof AuthenticatedScousGiftCardExchangeAdminClosuresRoute
  '/ScousGiftCardExchange/admin/mail': typeof AuthenticatedScousGiftCardExchangeAdminMailRoute
  '/ScousGiftCardExchange/admin/messages': typeof AuthenticatedScousGiftCardExchangeAdminMessagesRoute
  '/ScousGiftCardExchange/admin/rates': typeof AuthenticatedScousGiftCardExchangeAdminRatesRoute
  '/ScousGiftCardExchange/admin/trades': typeof AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren
  '/ScousGiftCardExchange/admin/users': typeof AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren
  '/ScousGiftCardExchange/admin/withdrawals': typeof AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute
  '/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
  '/ScousGiftCardExchange/admin': typeof AuthenticatedScousGiftCardExchangeAdminIndexRoute
  '/app/history': typeof AuthenticatedAppHistoryIndexRoute
  '/ScousGiftCardExchange/admin/trades/$id': typeof AuthenticatedScousGiftCardExchangeAdminTradesIdRoute
  '/ScousGiftCardExchange/admin/users/$id': typeof AuthenticatedScousGiftCardExchangeAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-help': typeof AccountHelpRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/avatar': typeof ApiAvatarRoute
  '/api/support': typeof ApiSupportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/login_/verify': typeof LoginVerifyRoute
  '/_authenticated/ScousGiftCardExchange/admin': typeof AuthenticatedScousGiftCardExchangeAdminRouteWithChildren
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/trade': typeof AuthenticatedAppTradeRoute
  '/_authenticated/app/withdraw': typeof AuthenticatedAppWithdrawRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/ScousGiftCardExchange/admin/audit': typeof AuthenticatedScousGiftCardExchangeAdminAuditRoute
  '/_authenticated/ScousGiftCardExchange/admin/closures': typeof AuthenticatedScousGiftCardExchangeAdminClosuresRoute
  '/_authenticated/ScousGiftCardExchange/admin/mail': typeof AuthenticatedScousGiftCardExchangeAdminMailRoute
  '/_authenticated/ScousGiftCardExchange/admin/messages': typeof AuthenticatedScousGiftCardExchangeAdminMessagesRoute
  '/_authenticated/ScousGiftCardExchange/admin/rates': typeof AuthenticatedScousGiftCardExchangeAdminRatesRoute
  '/_authenticated/ScousGiftCardExchange/admin/trades': typeof AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren
  '/_authenticated/ScousGiftCardExchange/admin/users': typeof AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren
  '/_authenticated/ScousGiftCardExchange/admin/withdrawals': typeof AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute
  '/_authenticated/app/history/$tradeId': typeof AuthenticatedAppHistoryTradeIdRoute
  '/_authenticated/ScousGiftCardExchange/admin/': typeof AuthenticatedScousGiftCardExchangeAdminIndexRoute
  '/_authenticated/app/history/': typeof AuthenticatedAppHistoryIndexRoute
  '/_authenticated/ScousGiftCardExchange/admin/trades/$id': typeof AuthenticatedScousGiftCardExchangeAdminTradesIdRoute
  '/_authenticated/ScousGiftCardExchange/admin/users/$id': typeof AuthenticatedScousGiftCardExchangeAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-help'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/app'
    | '/api/avatar'
    | '/api/support'
    | '/api/uploads'
    | '/login/verify'
    | '/ScousGiftCardExchange/admin'
    | '/app/chat'
    | '/app/history'
    | '/app/notifications'
    | '/app/settings'
    | '/app/trade'
    | '/app/withdraw'
    | '/api/files/$'
    | '/api/public/health'
    | '/app/'
    | '/ScousGiftCardExchange/admin/audit'
    | '/ScousGiftCardExchange/admin/closures'
    | '/ScousGiftCardExchange/admin/mail'
    | '/ScousGiftCardExchange/admin/messages'
    | '/ScousGiftCardExchange/admin/rates'
    | '/ScousGiftCardExchange/admin/trades'
    | '/ScousGiftCardExchange/admin/users'
    | '/ScousGiftCardExchange/admin/withdrawals'
    | '/app/history/$tradeId'
    | '/ScousGiftCardExchange/admin/'
    | '/app/history/'
    | '/ScousGiftCardExchange/admin/trades/$id'
    | '/ScousGiftCardExchange/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-help'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/api/avatar'
    | '/api/support'
    | '/api/uploads'
    | '/login/verify'
    | '/app/chat'
    | '/app/notifications'
    | '/app/settings'
    | '/app/trade'
    | '/app/withdraw'
    | '/api/files/$'
    | '/api/public/health'
    | '/app'
    | '/ScousGiftCardExchange/admin/audit'
    | '/ScousGiftCardExchange/admin/closures'
    | '/ScousGiftCardExchange/admin/mail'
    | '/ScousGiftCardExchange/admin/messages'
    | '/ScousGiftCardExchange/admin/rates'
    | '/ScousGiftCardExchange/admin/trades'
    | '/ScousGiftCardExchange/admin/users'
    | '/ScousGiftCardExchange/admin/withdrawals'
    | '/app/history/$tradeId'
    | '/ScousGiftCardExchange/admin'
    | '/app/history'
    | '/ScousGiftCardExchange/admin/trades/$id'
    | '/ScousGiftCardExchange/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-help'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/rates'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/app'
    | '/api/avatar'
    | '/api/support'
    | '/api/uploads'
    | '/login_/verify'
    | '/_authenticated/ScousGiftCardExchange/admin'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/history'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/trade'
    | '/_authenticated/app/withdraw'
    | '/api/files/$'
    | '/api/public/health'
    | '/_authenticated/app/'
    | '/_authenticated/ScousGiftCardExchange/admin/audit'
    | '/_authenticated/ScousGiftCardExchange/admin/closures'
    | '/_authenticated/ScousGiftCardExchange/admin/mail'
    | '/_authenticated/ScousGiftCardExchange/admin/messages'
    | '/_authenticated/ScousGiftCardExchange/admin/rates'
    | '/_authenticated/ScousGiftCardExchange/admin/trades'
    | '/_authenticated/ScousGiftCardExchange/admin/users'
    | '/_authenticated/ScousGiftCardExchange/admin/withdrawals'
    | '/_authenticated/app/history/$tradeId'
    | '/_authenticated/ScousGiftCardExchange/admin/'
    | '/_authenticated/app/history/'
    | '/_authenticated/ScousGiftCardExchange/admin/trades/$id'
    | '/_authenticated/ScousGiftCardExchange/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountHelpRoute: typeof AccountHelpRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiSupportRoute: typeof ApiSupportRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-help': {
      id: '/account-help'
      path: '/account-help'
      fullPath: '/account-help'
      preLoaderRoute: typeof AccountHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/verify': {
      id: '/login_/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ScousGiftCardExchange/admin': {
      id: '/_authenticated/ScousGiftCardExchange/admin'
      path: '/ScousGiftCardExchange/admin'
      fullPath: '/ScousGiftCardExchange/admin'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trade': {
      id: '/_authenticated/app/trade'
      path: '/trade'
      fullPath: '/app/trade'
      preLoaderRoute: typeof AuthenticatedAppTradeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/withdraw': {
      id: '/_authenticated/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AuthenticatedAppWithdrawRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ScousGiftCardExchange/admin/': {
      id: '/_authenticated/ScousGiftCardExchange/admin/'
      path: '/'
      fullPath: '/ScousGiftCardExchange/admin/'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminIndexRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/audit': {
      id: '/_authenticated/ScousGiftCardExchange/admin/audit'
      path: '/audit'
      fullPath: '/ScousGiftCardExchange/admin/audit'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminAuditRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/closures': {
      id: '/_authenticated/ScousGiftCardExchange/admin/closures'
      path: '/closures'
      fullPath: '/ScousGiftCardExchange/admin/closures'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminClosuresRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/mail': {
      id: '/_authenticated/ScousGiftCardExchange/admin/mail'
      path: '/mail'
      fullPath: '/ScousGiftCardExchange/admin/mail'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminMailRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/messages': {
      id: '/_authenticated/ScousGiftCardExchange/admin/messages'
      path: '/messages'
      fullPath: '/ScousGiftCardExchange/admin/messages'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/rates': {
      id: '/_authenticated/ScousGiftCardExchange/admin/rates'
      path: '/rates'
      fullPath: '/ScousGiftCardExchange/admin/rates'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminRatesRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/trades': {
      id: '/_authenticated/ScousGiftCardExchange/admin/trades'
      path: '/trades'
      fullPath: '/ScousGiftCardExchange/admin/trades'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminTradesRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/users': {
      id: '/_authenticated/ScousGiftCardExchange/admin/users'
      path: '/users'
      fullPath: '/ScousGiftCardExchange/admin/users'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminUsersRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/withdrawals': {
      id: '/_authenticated/ScousGiftCardExchange/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/ScousGiftCardExchange/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminRoute
    }
    '/_authenticated/app/history/': {
      id: '/_authenticated/app/history/'
      path: '/'
      fullPath: '/app/history/'
      preLoaderRoute: typeof AuthenticatedAppHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppHistoryRoute
    }
    '/_authenticated/app/history/$tradeId': {
      id: '/_authenticated/app/history/$tradeId'
      path: '/$tradeId'
      fullPath: '/app/history/$tradeId'
      preLoaderRoute: typeof AuthenticatedAppHistoryTradeIdRouteImport
      parentRoute: typeof AuthenticatedAppHistoryRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/trades/$id': {
      id: '/_authenticated/ScousGiftCardExchange/admin/trades/$id'
      path: '/$id'
      fullPath: '/ScousGiftCardExchange/admin/trades/$id'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminTradesIdRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminTradesRoute
    }
    '/_authenticated/ScousGiftCardExchange/admin/users/$id': {
      id: '/_authenticated/ScousGiftCardExchange/admin/users/$id'
      path: '/$id'
      fullPath: '/ScousGiftCardExchange/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedScousGiftCardExchangeAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedScousGiftCardExchangeAdminUsersRoute
    }
  }
}

interface AuthenticatedAppHistoryRouteChildren {
  AuthenticatedAppHistoryTradeIdRoute: typeof AuthenticatedAppHistoryTradeIdRoute
  AuthenticatedAppHistoryIndexRoute: typeof AuthenticatedAppHistoryIndexRoute
}

const AuthenticatedAppHistoryRouteChildren: AuthenticatedAppHistoryRouteChildren =
  {
    AuthenticatedAppHistoryTradeIdRoute: AuthenticatedAppHistoryTradeIdRoute,
    AuthenticatedAppHistoryIndexRoute: AuthenticatedAppHistoryIndexRoute,
  }

const AuthenticatedAppHistoryRouteWithChildren =
  AuthenticatedAppHistoryRoute._addFileChildren(
    AuthenticatedAppHistoryRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTradeRoute: typeof AuthenticatedAppTradeRoute
  AuthenticatedAppWithdrawRoute: typeof AuthenticatedAppWithdrawRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTradeRoute: AuthenticatedAppTradeRoute,
  AuthenticatedAppWithdrawRoute: AuthenticatedAppWithdrawRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedScousGiftCardExchangeAdminTradesRouteChildren {
  AuthenticatedScousGiftCardExchangeAdminTradesIdRoute: typeof AuthenticatedScousGiftCardExchangeAdminTradesIdRoute
}

const AuthenticatedScousGiftCardExchangeAdminTradesRouteChildren: AuthenticatedScousGiftCardExchangeAdminTradesRouteChildren =
  {
    AuthenticatedScousGiftCardExchangeAdminTradesIdRoute:
      AuthenticatedScousGiftCardExchangeAdminTradesIdRoute,
  }

const AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren =
  AuthenticatedScousGiftCardExchangeAdminTradesRoute._addFileChildren(
    AuthenticatedScousGiftCardExchangeAdminTradesRouteChildren,
  )

interface AuthenticatedScousGiftCardExchangeAdminUsersRouteChildren {
  AuthenticatedScousGiftCardExchangeAdminUsersIdRoute: typeof AuthenticatedScousGiftCardExchangeAdminUsersIdRoute
}

const AuthenticatedScousGiftCardExchangeAdminUsersRouteChildren: AuthenticatedScousGiftCardExchangeAdminUsersRouteChildren =
  {
    AuthenticatedScousGiftCardExchangeAdminUsersIdRoute:
      AuthenticatedScousGiftCardExchangeAdminUsersIdRoute,
  }

const AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren =
  AuthenticatedScousGiftCardExchangeAdminUsersRoute._addFileChildren(
    AuthenticatedScousGiftCardExchangeAdminUsersRouteChildren,
  )

interface AuthenticatedScousGiftCardExchangeAdminRouteChildren {
  AuthenticatedScousGiftCardExchangeAdminAuditRoute: typeof AuthenticatedScousGiftCardExchangeAdminAuditRoute
  AuthenticatedScousGiftCardExchangeAdminClosuresRoute: typeof AuthenticatedScousGiftCardExchangeAdminClosuresRoute
  AuthenticatedScousGiftCardExchangeAdminMailRoute: typeof AuthenticatedScousGiftCardExchangeAdminMailRoute
  AuthenticatedScousGiftCardExchangeAdminMessagesRoute: typeof AuthenticatedScousGiftCardExchangeAdminMessagesRoute
  AuthenticatedScousGiftCardExchangeAdminRatesRoute: typeof AuthenticatedScousGiftCardExchangeAdminRatesRoute
  AuthenticatedScousGiftCardExchangeAdminTradesRoute: typeof AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren
  AuthenticatedScousGiftCardExchangeAdminUsersRoute: typeof AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren
  AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute: typeof AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute
  AuthenticatedScousGiftCardExchangeAdminIndexRoute: typeof AuthenticatedScousGiftCardExchangeAdminIndexRoute
}

const AuthenticatedScousGiftCardExchangeAdminRouteChildren: AuthenticatedScousGiftCardExchangeAdminRouteChildren =
  {
    AuthenticatedScousGiftCardExchangeAdminAuditRoute:
      AuthenticatedScousGiftCardExchangeAdminAuditRoute,
    AuthenticatedScousGiftCardExchangeAdminClosuresRoute:
      AuthenticatedScousGiftCardExchangeAdminClosuresRoute,
    AuthenticatedScousGiftCardExchangeAdminMailRoute:
      AuthenticatedScousGiftCardExchangeAdminMailRoute,
    AuthenticatedScousGiftCardExchangeAdminMessagesRoute:
      AuthenticatedScousGiftCardExchangeAdminMessagesRoute,
    AuthenticatedScousGiftCardExchangeAdminRatesRoute:
      AuthenticatedScousGiftCardExchangeAdminRatesRoute,
    AuthenticatedScousGiftCardExchangeAdminTradesRoute:
      AuthenticatedScousGiftCardExchangeAdminTradesRouteWithChildren,
    AuthenticatedScousGiftCardExchangeAdminUsersRoute:
      AuthenticatedScousGiftCardExchangeAdminUsersRouteWithChildren,
    AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute:
      AuthenticatedScousGiftCardExchangeAdminWithdrawalsRoute,
    AuthenticatedScousGiftCardExchangeAdminIndexRoute:
      AuthenticatedScousGiftCardExchangeAdminIndexRoute,
  }

const AuthenticatedScousGiftCardExchangeAdminRouteWithChildren =
  AuthenticatedScousGiftCardExchangeAdminRoute._addFileChildren(
    AuthenticatedScousGiftCardExchangeAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedScousGiftCardExchangeAdminRoute: typeof AuthenticatedScousGiftCardExchangeAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedScousGiftCardExchangeAdminRoute:
    AuthenticatedScousGiftCardExchangeAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountHelpRoute: AccountHelpRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiSupportRoute: ApiSupportRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
